"use client";

import { motion } from "framer-motion";

const sections = [
  {
    title: "Operational Estimation Platform",
    body: `
Karpilo LoadIQ (“LoadIQ”) is an operational estimation and freight profitability analysis platform developed by Karpilo Endeavor Technologies LLC.

LoadIQ is designed to assist owner-operators, carriers, dispatchers, and transportation professionals in evaluating operational variables such as deadhead exposure, operating cost, fuel cost, RPM, margin pressure, and estimated profitability before accepting freight.

LoadIQ is intended solely as a decision-support and operational visibility tool.
    `,
  },
  {
    title: "No Financial, Tax, Legal, or Dispatch Advice",
    body: `
LoadIQ does not provide legal advice, accounting advice, tax advice, financial advice, compliance certification, brokerage services, or dispatch authority.

Any calculations, projections, estimates, profitability indicators, or operational recommendations generated by the platform are informational estimates only and should not be interpreted as guaranteed financial outcomes or professional advisory guidance.

Users are solely responsible for operational decisions, load acceptance decisions, routing decisions, financial analysis, tax reporting, compliance obligations, and business outcomes.
    `,
  },
  {
    title: "User Responsibility",
    body: `
Users are responsible for ensuring the accuracy of all submitted operational data, including but not limited to:
- fuel cost inputs
- mileage
- deadhead mileage
- maintenance assumptions
- insurance expenses
- operating overhead
- accessorial charges
- dispatch information
- rate confirmation values
- tax assumptions
- cost-per-mile assumptions

Inaccurate or incomplete inputs may produce inaccurate profitability estimates or operational outputs.
    `,
  },
  {
    title: "No Guaranteed Profitability",
    body: `
Karpilo Endeavor Technologies LLC makes no guarantee that any load, route, customer, broker, dispatch decision, or operational strategy evaluated through LoadIQ will result in profitability, financial gain, operational success, or business performance improvements.

Transportation operations involve variables outside the platform’s control including:
- fuel volatility
- weather
- traffic
- detention
- maintenance failures
- compliance events
- rate fluctuations
- driver behavior
- market conditions
- broker disputes
- operational inefficiencies

Actual financial results may vary substantially.
    `,
  },
  {
    title: "Platform Availability",
    body: `
Karpilo Endeavor Technologies LLC may modify, suspend, restrict, discontinue, or update portions of the platform at any time without prior notice.

Features, calculations, subscription structures, founding access programs, launch incentives, and operational modules may change during development and after release.
    `,
  },
  {
    title: "Subscription & Founding Access",
    body: `
Certain portions of LoadIQ may require paid subscriptions, early-access enrollment, or founding operator participation.

Pricing, promotional incentives, subscription duration, launch access, and future feature availability are subject to change.

Any future subscriptions offered through Apple App Store or Google Play will be governed by their respective billing and subscription policies in addition to these Terms.
    `,
  },
  {
    title: "Limitation of Liability",
    body: `
To the maximum extent permitted by applicable law, Karpilo Endeavor Technologies LLC shall not be liable for:
- business interruption
- lost revenue
- lost profits
- operational losses
- dispatch losses
- fuel losses
- indirect damages
- consequential damages
- reliance on calculations
- routing decisions
- broker disputes
- compliance penalties
- operational outcomes

Use of the platform is at the user’s sole discretion and operational risk.
    `,
  },
  {
    title: "Intellectual Property",
    body: `
All platform branding, interface systems, visual assets, operational concepts, trademarks, software architecture, and platform materials associated with Karpilo LoadIQ and Karpilo Endeavor Technologies LLC remain protected intellectual property unless otherwise stated.
    `,
  },
  {
    title: "Contact Information",
    body: `
Karpilo Endeavor Technologies LLC

Website:
www.karpiloendeavortechnologies.com

Contact:
karpiloloadiq@karpiloendeavortechnologies.com
    `,
  },
];

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#020617] text-white">
      <div className="pointer-events-none fixed inset-0">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,rgba(56,189,248,0.16),transparent_30%),radial-gradient(circle_at_85%_20%,rgba(239,68,68,0.12),transparent_26%),linear-gradient(to_bottom,#020617,#020617)]" />

        <div className="absolute inset-0 opacity-[0.12] bg-[linear-gradient(rgba(255,255,255,0.05)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.05)_1px,transparent_1px)] bg-[size:72px_72px]" />
      </div>

      <section className="relative z-10 mx-auto max-w-5xl px-6 py-20 sm:px-8">
        <motion.div
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-16"
        >
          <div className="inline-flex rounded-full border border-red-500/30 bg-red-500/10 px-5 py-2 text-xs font-black uppercase tracking-[0.22em] text-red-200">
            Terms & Conditions
          </div>

          <h1 className="mt-8 text-5xl font-black tracking-[-0.06em] sm:text-6xl">
            Karpilo LoadIQ Terms of Service
          </h1>

          <p className="mt-8 max-w-3xl text-lg leading-8 text-slate-300">
            These Terms govern the use of Karpilo LoadIQ and related
            operational estimation services provided by Karpilo Endeavor Technologies LLC.
          </p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((section, index) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 18 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.06 }}
              className="rounded-[2rem] border border-white/10 bg-[#0B1120]/80 p-8 shadow-[0_0_34px_rgba(56,189,248,0.06)]"
            >
              <h2 className="text-2xl font-black tracking-[-0.03em] text-white">
                {section.title}
              </h2>

              <div className="mt-5 whitespace-pre-line leading-8 text-slate-300">
                {section.body}
              </div>
            </motion.div>
          ))}
        </div>

        <div className="mt-16 rounded-[2rem] border border-red-500/20 bg-red-500/5 p-8">
          <p className="text-sm leading-7 text-slate-400">
            These Terms are provided as an operational launch framework
            and may be updated, revised, or expanded as Karpilo LoadIQ evolves.
          </p>
        </div>
      </section>
    </main>
  );
}